stages:
  data_ingestion:
    cmd: python sentiment/src/data/data_ingestion.py
    deps:
    - sentiment/src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  preprocessing:
    cmd: python sentiment/src/features/preprocessing.py
    deps:
    - ./data/raw
    - sentiment/src/features/preprocessing.py
    outs:
    - ./data/interim
  feature_engineering:
    cmd: python sentiment/src/features/feature_engineering.py
    deps:
    - ./data/interim
    - sentiment/src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - ./data/processed
  model_building:
    cmd: python sentiment/src/model/model_building.py
    params:
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    deps:
    - ./data/processed
    - sentiment/src/model/model_building.py
    outs:
    - sentiment/models/model.pkl
  model_evaluation:
    cmd: python sentiment/src/model/model_evaluation.py
    deps:
    - sentiment/models/model.pkl
    - sentiment/src/model/model_evaluation.py
    outs:
    - sentiment/reports/metrics.json